steps:
  # Build the image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--network=cloudbuild",
        "-t",
        "$_ARTIFACT_REGISTRY_REGION-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_ARTIFACT_REGISTRY_IMAGE_NAME:$COMMIT_SHA",
        ".",
      ]

  # Push the image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "$_ARTIFACT_REGISTRY_REGION-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_ARTIFACT_REGISTRY_IMAGE_NAME:$COMMIT_SHA",
      ]

  # Deploy image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "$_CLOUD_RUN_SERVICE_NAME",
        "--image",
        "$_ARTIFACT_REGISTRY_REGION-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_ARTIFACT_REGISTRY_IMAGE_NAME:$COMMIT_SHA",
        "--region",
        "$_CLOUD_RUN_REGION",
        "--set-env-vars",
        "FINANCIAL_MODELING_PREP_API_KEY=$$FINANCIAL_MODELING_PREP_API_KEY",
        "--allow-unauthenticated",
      ]
    secretEnv: ["FINANCIAL_MODELING_PREP_API_KEY"]

images:
  - "$_ARTIFACT_REGISTRY_REGION-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_ARTIFACT_REGISTRY_IMAGE_NAME:$COMMIT_SHA"

availableSecrets:
  secretManager:
    - versionName: "projects/cannytrading-prod/secrets/FINANCIAL_MODELING_PREP_API_KEY/versions/1"
      env: "FINANCIAL_MODELING_PREP_API_KEY"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID: cannytrading-prod
  _ARTIFACT_REGISTRY_REGION: us-west1
  _ARTIFACT_REGISTRY_REPO_NAME: web-repository
  _ARTIFACT_REGISTRY_IMAGE_NAME: main
  _CLOUD_RUN_REGION: us-west1
  _CLOUD_RUN_SERVICE_NAME: cannytrading-web
